name: Build and deploy Python app to Azure Web App - chatbotteams

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip ./* -x "venv/*" # Exclude the venv directory

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

      - name: Upload startup.sh as artifact
        uses: actions/upload-artifact@v4
        with:
          name: startup-script
          path: startup.sh

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Download startup.sh from build job
        uses: actions/download-artifact@v4
        with:
          name: startup-script

      - name: Unzip artifact for deployment
        run: unzip -o release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D4886E79261D4B03AA8C83DFB1A201A2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6B60E18729D14282BC7175F47ABD1759 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_426BBC44A796430EA6CCD9A877EFD740 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'chatbotteams'
          slot-name: 'Production'

      - name: Wait for Azure Web App initialization
        run: sleep 60  # Wait 60 seconds for initialization

      - name: Copy startup.sh to /home/site/wwwroot/
        run: |
          echo "Copying startup.sh to /home/site/wwwroot/"
          if [ -d /home/site/wwwroot ]; then
            cp startup.sh /home/site/wwwroot/startup.sh
          else
            echo "/home/site/wwwroot does not exist"
            exit 1
          fi
