name: Build and deploy Python app to Azure Web App - chatbotteams

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip -r release.zip ./* -x venv/\*

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d /tmp/deployment

      - name: Check for startup.sh
        run: |
          if [ -f /tmp/deployment/startup.sh ]; then
            echo "startup.sh found!"
          else
            echo "startup.sh not found!"
            exit 1
          fi

      - name: List contents of /tmp/deployment
        run: ls -la /tmp/deployment

      - name: Copy startup.sh to wwwroot
        run: |
          echo "Copying startup.sh to /home/site/wwwroot/"
          cp /tmp/deployment/startup.sh /home/site/wwwroot/
          ls -la /home/site/wwwroot/  # Verify if the file is copied

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D4886E79261D4B03AA8C83DFB1A201A2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6B60E18729D14282BC7175F47ABD1759 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_426BBC44A796430EA6CCD9A877EFD740 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'chatbotteams'
          slot-name: 'Production'
